name: staging
"on":
  push:
    branches:
      - master
jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPOSITORY_NAME }}
          registry: docker.io
          password: ${{ secrets.DOCKER_PASSWORD}}
          tag: latest
          username: ${{ secrets.DOCKER_USERNAME}}
      - run: docker inspect --format='{{index .RepoDigests 0}}' ${{ secrets.DOCKER_USERNAME }}/${REPOSITORY_NAME}:${GITHUB_REF_SLUG} > image_sha.txt
      - uses: actions/upload-artifact@v1
        with:
          name: image_sha
          path: image_sha.txt
